name: Deploy to Github

on:
  push:
    branches:
      - master

jobs:
  maven:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish package
        # These tests are not automated, skip them when ran
        run: mvn --batch-mode -DskipTests deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}